apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask
  namespace: prueba-flask
  labels:
    app: app-flask
spec:
  replicas: 2  # El número de réplicas que necesites
  selector:
    matchLabels:
      app: app-flask
  strategy:
    type: RollingUpdate  # Estrategia de actualización
    rollingUpdate:
      maxSurge: 1  # Máximo de pods adicionales durante la actualización
      maxUnavailable: 0  # Máximo de pods no disponibles durante la actualización
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
      - name: mi-app-flask
        image: fcongedo/app-flask:1
        ports:
        - containerPort: 5000